### ISSUE TITLE
v2ex浏览器显示的cookie好几个，哪个是？

### ISSUE THREAD

**Issue by catbreast** [Wenmoux/V2ex-Auto-Sign#1]

**Comment by Wenmoux** [comment]
全部阿  比如这 https://cdn.jsdelivr.net/gh/Wenmoux/wenpic/Screenshot_2020-06-30-06-59-26-446_com.tencent.mobileqq.jpg
刚刚点错了ヽ（・＿・；)ノ点了编辑问题
