### ISSUE TITLE
增加TgBot推送

### ISSUE THREAD

**Issue by Windyskr** [Wenmoux/V2ex-Auto-Sign#10]
已经改好了

https://github.com/Windyskr/V2ex-Auto-Sign

**Comment by Wenmoux** [comment]
感谢！！(>ω<)https://github.com/Wenmoux/V2ex-Auto-Sign/commit/6cb86e77a1b92501bc3c7aae40400b1bd3a505c8已添加

**Comment by Wenmoux** [comment]
skr emmm艾特错了 无视我
