### ISSUE TITLE
时间问题

### ISSUE THREAD

**Issue by noshore** [Wenmoux/V2ex-Auto-Sign#4]
我看了一下大佬的代码 好像定时的0 10 * * * 
github上时间需要+8 
定时的时间我自己已经改了 但是那个推送的时间也是UTC 不知道该怎么改一下 有点强迫症

**Comment by Wenmoux** [comment]
改下签到代码的第八行 给小时+8？😂

**Comment by noshore** [comment]
> 改下签到代码的第八行 给小时+8？

怎么改啊
time=new Date().toLocaleString()这一行吗 可以麻烦大佬写出来发到这吗 我不太会

**Comment by Wenmoux** [comment]
time = new Date();
tmpHours = time.getHours();
time.setHours(tmpHours + 8);
notice = time.toLocaleString() + "\n";
当然你也可以把它合一下

**Comment by noshore** [comment]
好的 谢谢大佬 我试试

**Comment by noshore** [comment]
> time = new Date();
> tmpHours = time.getHours();
> time.setHours(tmpHours + 8);
> notice = time.toLocaleString() + "\n";
> 当然你也可以把它合一下

好的 谢谢大佬 我试试
