### ISSUE TITLE
qmsg酱推送没成功

### ISSUE THREAD

**Issue by noshore** [Wenmoux/V2ex-Auto-Sign#6]
今天qmsg酱显示推送成功 但实则没推送 想问一下是qmsg的问题 还是脚本的问题

**Comment by Wenmoux** [comment]
你加对应的qq没 号上 加错了或者没加好友也收不到 我这里没问题

**Comment by noshore** [comment]
> 你加对应的qq没 号上 加错了或者没加好友也收不到 我这里没问题

加了的 前几天可以 但是今天突然不行了 我手动执行一次也没推送 不知道为啥

**Comment by noshore** [comment]
> 你加对应的qq没 号上 加错了或者没加好友也收不到 我这里没问题

好了 刚刚又手动测试了一下推送了 可能是github的原因 今天下午github炸了 上午没推送不知道为啥现在手动测试一下正常的
